#\src\model_serving\Dockerfile.bentoml
FROM python:3.9-slim

# BentoML 1.1.11
RUN pip install --no-cache-dir bentoml==1.1.11

# MLflow ve bağımlılıklar
RUN pip install mlflow "psycopg2-binary>=2.9" numpy pandas scikit-learn pydantic

WORKDIR /home/bentoml

COPY src/model_serving/service.py .

# DÜZELTME: VitalWatchService değil, svc kullan!
ENTRYPOINT [ "bentoml", "serve", "service.py:svc", "--host", "0.0.0.0", "--port", "3000" ]